version: 0.2

phases:
  pre_build:
    commands:
      - yarn install
  build:
    commands:
      - yarn start
      - yarn build

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: build
